#!/bin/sh
#
# Run this shell script to bootstrap as necessary after a fresh checkout.
#
# Copyright 2008, 2012-2013, 2016, 2018, 2024 Russ Allbery <eagle@eyrie.org>
#
# SPDX-License-Identifier: MIT

set -e

# Regenerate all the autotools files.
autoreconf -i --force

# Generate manual pages.
version=$(grep '^##' CHANGELOG.md | head -1 | cut -d' ' -f2)
for doc in xmalloc; do
    pod2man --release="$version" --center="rra-c-util" --section=3      \
        --name=$(echo "$doc" | tr a-z A-Z) docs/api/"$doc".pod          \
        > docs/api/"$doc".3
done
