#! /bin/sh
#
# mkusage -- Generate usage.c from from USAGE.
#
# The canonical version of this file is maintained in the rra-c-util package,
# which can be found at <http://www.eyrie.org/~eagle/software/rra-c-util/>.
#
# Copyright 2000 Russ Allbery <rra@stanford.edu>
#
# The authors hereby relinquish any claim to any copyright that they may have
# in this work, whether granted under contract or by operation of law or
# international treaty, and hereby commit to the public, at large, that they
# shall not, at any time in the future, seek to enforce any copyright in this
# work against any person or entity, or prevent any person or entity from
# copying, publishing, distributing or creating derivative works of this work.

echo '/* Generated automatically from USAGE by mkusage. */' > usage.c
echo '' >> usage.c
echo 'static const char usage_message[] =' >> usage.c
sed -e '1s/^/\"/' -e 's/$/\\n\\/' -e '$s/\\$/\";/' < USAGE >> usage.c
cat >> usage.c <<__EOC__

#include <stdio.h>
#include <stdlib.h>

void
usage(int status)
{
    fprintf(status ? stderr : stdout, usage_message);
    exit(status);
}
__EOC__
