# Perl dependencies for CI tests.   -*- perl -*-
#
# This file is used by cpanm to install dependencies used by the rra-c-util
# test suite.
#
# Copyright 2015-2020, 2022, 2025 Russ Allbery <eagle@eyrie.org>
#
# SPDX-License-Identifier: MIT

on 'test' => sub {
    suggests 'Devel::Cover';
    suggests 'IPC::System::Simple';
    suggests 'Perl6::Slurp';
    suggests 'Perl::Critic::Community';
    suggests 'Test::Kwalitee';
    suggests 'Test::MinimumVersion';
    suggests 'Test::Perl::Critic';
    suggests 'Test::Pod';
    suggests 'Test::Pod::Coverage';
    suggests 'Test::Spelling';
    suggests 'Test::Strict';
    suggests 'Test::Synopsis';
}
