# Perl dependencies for CI tests.   -*- perl -*-
#
# This file is used by cpanm to install dependencies used by the rra-c-util
# test suite.
#
# Copyright 2015-2020 Russ Allbery <eagle@eyrie.org>
#
# SPDX-License-Identifier: MIT

on 'test' => sub {
    requires 'Devel::Cover';
    requires 'IPC::System::Simple';
    requires 'Perl::Critic::Freenode';
    requires 'Test::MinimumVersion';
    requires 'Test::Perl::Critic';
    requires 'Test::Pod';
    requires 'Test::Pod::Coverage';
    requires 'Test::Spelling';
    requires 'Test::Strict';
    requires 'Test::Synopsis';
}
