#!/bin/sh
#
# Install packages for integration tests.
#
# This script is normally run via sudo in a test container or VM, such as via
# GitHub Actions.  Additional prerequisites are installed (and cached)
# directly from the workflow in .github/workflows/build.yaml.
#
# Copyright 2015-2020 Russ Allbery <eagle@eyrie.org>
#
# SPDX-License-Identifier: MIT

set -eux

# Install apt packages.
apt-get update
apt-get install $(grep -v '^#' ci/apt-packages)

# If not running as a GitHub workflow, also install Perl packages.  Under the
# GitHub workflow, this will be done (and cached) by actions.
if [ -z "${GITHUB_WORKFLOW:-}" ]; then
    cpanm --notest --cpanfile ci/cpanfile --installdeps .
fi
