#!/bin/sh
#
# Run tests for continuous integration.
#
# This script is normally run in a test container or VM, such as via GitHub
# Actions.
#
# Copyright 2015-2020, 2024-2025 Russ Allbery <eagle@eyrie.org>
#
# SPDX-License-Identifier: MIT

set -eux

# Configure Perl to use the cpanm installation paths.
eval "$(perl -Mlocal::lib)"

# Build everything with Clang with compiler warnings.
./bootstrap
./configure CC=clang
make warnings

# Rebuild everything with GCC for more compiler warnings.
make distclean
./configure CC=gcc
make warnings

# Run the test suite including for the Perl helpers.
make check

# Test with valgrind.
make check-valgrind

# Run some additional checks.  (Temporarily disabled until the GitHub runners
# use a new enough version of cppcheck to support --check-level=exhaustive.)
#make check-cppcheck
