#!/bin/sh
#
# Run tests for continuous integration.
#
# This script is normally run in a test container or VM, such as via GitHub
# Actions.
#
# Copyright 2015-2020 Russ Allbery <eagle@eyrie.org>
#
# SPDX-License-Identifier: MIT

set -eux

# Build everything with Clang.
./bootstrap
./configure CC=clang
make warnings

# Rebuild everything with GCC for more compiler warnings.
make distclean
./configure CC=gcc
make warnings

# Test with valgrind.
make check-valgrind

# Run some additional checks.
make check-cppcheck
